### ISSUE TITLE
Move from ElaoInfra/* to Manala/*

### ISSUE THREAD

**Issue by chalasr** [manala/manalize#1]

**Comment by nervo** [comment]
Do you want the project be moved on the manala github organization ?

(you can say no, no offense)

**Comment by chalasr** [comment]
That's the first intention so yes, I _do_ want :) 
Of course, If you can envisage me as part of the org, sir? In order to let me do my best to make it grows as possible, then promoting and maintaining it as well.

At this moment I'm working closing this issue and adding tests for the single command (that shouldn't stay single for long, as we discussed).

**Comment by nervo** [comment]
Stop it,you have been just invited :)

**Comment by chalasr** [comment]
Thank you @nervo.

So, we'll need to change the namespace from `RCH\Manalize` to `Manala\Manalize`(the `Manalize` being potentially not permanent), right? Then, register the `manala` vendor on packagist (we're very lucky, it seems to be [available](packagist.org/packages/manala))

**Comment by nervo** [comment]
- [x] Register manala vendor on packagist (nice catch, btw)
- [x] Help you to change the namespace (tomorrow, i'm tired right now, and feel the urge to see the 5th episode of stranger things)

:kiss:

**Comment by chalasr** [comment]
Done just before transfer, this is now part of @manala :)

Next steps:
- [x] Do something for closing this and all opened issues (see #6)
- [x] Add tests
- [ ] Put this on TravisCI/StyleCI/ScrutinizerCI and so on...
- [ ] Write an awesome README with lots of ugly labels from *CI
- [ ] Add lots of commands
- [ ] Stuck on naming

_Do not hesitate_ to shout me about the existing or propose/break/remove/add anything.

💄
