### ISSUE TITLE
Synchronisation basique des templates

### ISSUE THREAD

**Issue by nervo** [manala/manalize#108]
Dans le fichier local manala.yml
```
template:
  name: elao-symfony
```

Fait reference a https://github.com/manala/manalize-templates/tree/master/elao-symfony

- On parse le manala.yml local pour récupérer le nom du template
- On télécharge et decompresse https://codeload.github.com/manala/manalize-templates/tar.gz/master (temp ? memory ?)
- On synchronise de manière bourrine le repertoire manala local en fonction du nom du template (suppression des fichiers orphelins ?)

Bisous

**Comment by chalasr** [comment]
Fixed in #110
