### ISSUE TITLE
[setup] If no --env is passed then display a choice of all templates instead of going with "custom"

### ISSUE THREAD

**Issue by chalasr** [manala/manalize#115]
When using the `manalize setup` command, if no `--env` is passed then we assume the user wants a fully custom environment (no template with predefined set of dependencies).
We would better let him choose one of our templates (see https://github.com/manala/manalize/blob/master/src/Env/EnvName.php, it contains `CUSTOM` so if user wants custom it's ok).

See http://api.symfony.com/3.3/Symfony/Component/Console/Style/SymfonyStyle.html#method_choice

**Comment by xavier-rdo** [comment]
PR (WIP) : https://github.com/manala/manalize/pull/119/files
