### ISSUE TITLE
Reminder

### ISSUE THREAD

**Issue by nervo** [manala/manalize#130]
- [x] "{{ lookup('pipe','git ls-remote --get-url origin') }}”
- [x]  Node 8
- [x] Elasticsearch 5

**Comment by ogizanagi** [comment]
Node 8 already added in https://github.com/manala/manalize/pull/126 (but not on the https://github.com/manala/manalize-templates repo)

**Comment by chalasr** [comment]
Remaining ones fixed in #131 and #133
