### ISSUE TITLE
disable sqlite by default

### ISSUE THREAD

**Issue by mb3rnard** [manala/manalize#148]
if mysql is the most common used SGBD, I believe sqlite should not be installed by default.

**Comment by chalasr** [comment]
That's desired, reasoning can be found in https://github.com/manala/manalize/pull/132.
No strong opinion, IMHO it does not hurt.  ping @ogizanagi

**Comment by mb3rnard** [comment]
I found it redundant to have 2 SGDB installed by default, but I understand the need for in memory tests explained by @ogizanagi, especially in the context of a Symfony project.
