### ISSUE TITLE
Issue with custom Twig delimiters 

### ISSUE THREAD

**Issue by Kocal** [manala/manalize#164]
Hi,

Just to let you know, there is an issue with Twig when using custom tags delimiters that contain `#`, like `{#` and `[#`:
```
PHP Warning:  preg_match_all(): Compilation failed: missing ) at offset 51 in /home/kocal/.composer/vendor/twig/twig/src/Lexer.php on line 169
```

It makes Manalize unusable with PHP <7.3 because generated files are not being computed by Twig. 
For example this is what my `Vagrantfile` looks like:
```
{% extends "common/Vagrantfile" %}
```

I've opened an issue https://github.com/twigphp/Twig/issues/2948 for this.

**Comment by chalasr** [comment]
Thanks for raising. Changing our delimiters to not use `#` is probably the easiest alternative

**Comment by Kocal** [comment]
By the way a fix has been applied (https://github.com/twigphp/Twig/pull/2949).
We can also _just wait_ for a new Twig release.

**Comment by chalasr** [comment]
Nice!

**Comment by Kocal** [comment]
Twig 1.40.0 and 2.9.0 have been released since ~20 days, I think we can close this issue.
