### ISSUE TITLE
Feature: check command

### ISSUE THREAD

**Issue by chalasr** [manala/manalize#17]
We need a command that checks if the user is ready to use this tool and give it an output with all the problems and the solutions to solve them.

We have to check
- If vagrant is installed with the correct version (> 1.8.4)
- If ansible is installed with the correct version (> 2.0.0)
- ? Maybe some other stuff I miss

For all of those checks, we want to provide a quick way to correct it if it doesn't pass, e.g:

> Your vagrant version `xxx` doesn't allow you to use this. Please upgrade to `1.8.4` by downloading the installer from this link `xxx`.

A bonus could be to adapt the advice depending on if the user is on OSX or linux (see the `PHP_OS` php constant). 

Note: we do not want to exit on the first missing check. We need to give a final output with all failed checks at once, so the end user can solve them one by one.

Resources: 
- Creating a console command: http://symfony.com/doc/current/console.html
- Testing it: http://symfony.com/doc/current/console.html#testing-commands
- A nice way to run bash commands for doing the checks from the main Console command: http://symfony.com/doc/current/components/process.html

ping @xavier-rdo If you'd help :)

**Comment by ogizanagi** [comment]
Closed by #19 ?
