### ISSUE TITLE
Manalize PHP 7.4 compatibility

### ISSUE THREAD

**Issue by NicolasDievart** [manala/manalize#171]
Hi !

It seems that manalize is not compatible with php 7.4 as it uses https://github.com/nikic/iter version ^1.4 and only version ^2 of the dependency is compatible with it (https://github.com/nikic/iter/releases/tag/v2.0.0).

@benji07 started a PR with the update : https://github.com/manala/manalize/pull/170

Is there anything blocking with it ?
Is it still the way to go with the rework in go of Manala ?

**Comment by ogizanagi** [comment]
Should be fixed by https://github.com/manala/manalize/releases/tag/v0.10.2

`manalize selfupdate`

**Comment by NicolasDievart** [comment]
Thank you @ogizanagi :+1:
