### ISSUE TITLE
Better output catching during build

### ISSUE THREAD

**Issue by chalasr** [manala/manalize#20]
I would like to see the error during the `build` process better caught, thinking to have only the output of the vagrant provisioning subtask that have failed. 

We need to dig but I hope storing `stderr` in "real time" during the process execution will be enough (do not give the whole output like `Build::getErrorOutput()` seems to do actually) so we can add the precise error output to the final `fail` warning and enjoy at time to understand what did happen in the failed build.

**Comment by ogizanagi** [comment]
Will be closed by #33 I guess :)
