### ISSUE TITLE
Destroy virtual machine on failed build

### ISSUE THREAD

**Issue by chalasr** [manala/manalize#21]
Avoiding conflicts on next builds, allowing retry and such.

**Comment by ogizanagi** [comment]
Is this issue still relevant ?

**Comment by chalasr** [comment]
Unfortunately it is, but no more actionable.
Vagrant let a weird state on the host after a fail, it's often that NFS exports aren't properly cleaned for instance and the machine isn't removed

But I'll profit to avoid a doubt, when a build fail I get a secondary warning saying "could not retrieve file app.retry", maybe having this file could help in this way? I'll investigate

**Comment by chalasr** [comment]
At the moment, we can't do anything for that
