### ISSUE TITLE
The vendor name should not be required

### ISSUE THREAD

**Issue by benji07** [manala/manalize#28]
I want to create a simple app without vendor name (to have a domain like app.dev and not app.vendor.dev)

**Comment by chalasr** [comment]
You're right. 
Also I am thinking to avoid asking vendor+app and just ask the hostname instead, but I'm not aware of the eventual side effects. What do you think? This is how [laravel homestead](https://github.com/laravel/homestead/blob/master/src/MakeCommand.php#L48) does it for instance.

ping @nervo @ogizanagi @xavier-rdo @hyvs
