### ISSUE TITLE
Unexisting packages installed as php extensions for php5

### ISSUE THREAD

**Issue by chalasr** [manala/manalize#50]
`php5-mbstring`, `php5-xml` and `php5-zip` packages do not exist. 
But when they are enabled in `php_extensions` as `mbstring` `xml` and `zip`, and the php version is set to `5.*`, the `manala/ansible-role-php` role tries to install them as packages which causes a failed `make setup`. This bug concerns both this project and `elao/symfony-standard` and should be fixed on the role itself. 

If nothing can be done on the role itself, an alternative could be to do not add these extensions to the `php_extensions` array if php 5 is used. Imho it's weird, but it would work at least.

**Comment by gfaivre** [comment]
For now we had chosen to handle it at the extension definition level as below (phpmyadmin example):

```
php_extensions: "{{
    []
    + (infra_options.phpmyadmin)|ternary(
        {
          '5.4':['mysql'],
          '5.5':['mysqlnd'],
          '5.6':['mysqlnd'],
          '7.0':['mysql', 'mbstring', 'zip', 'bz2']
        }[infra_options.php_version|string],
        []
      )
  }}"
```

@nervo is working on a workaround at the role level.

**Comment by chalasr** [comment]
I can make it work using the following:

``` yaml
php_extensions: "{{ (app_options.php_version|string == '7.0')|ternary(['intl', 'curl', 'gd', 'mbstring', 'zip', 'xml'], ['intl', 'curl', 'gd']) }}"
```

But that's far from user friendly...
ping @nervo :)

edit: should be fixed by https://github.com/manala/ansible-role-php/pull/5

**Comment by chalasr** [comment]
Fixed by https://github.com/manala/ansible-role-php/pull/5 🎉
