### ISSUE TITLE
Consider moving to PHP 7

### ISSUE THREAD

**Issue by ogizanagi** [manala/manalize#63]
- According to [PHP's Roadmap](http://php.net/supported-versions.php), PHP 5.6 will be actively supported only up to 1st January 2017.
- Until Manalize is spread _all around the world_, PHP 7 will be the norm.
- Manalize is a tool used by developers, on their own machines. It should not be an issue, as any respectful developer should have the latest PHP version installed. :p 
- We're depriving ourself from using some really cool features (see https://github.com/manala/manalize/pull/62#issuecomment-256407154 for instance)
- Really ? :trollface:

**Comment by chalasr** [comment]
I first started to repeat all of my arguments and... after all, I think you're right.

For linux, PHP 7.0 is the default version installed on the latest Ubuntu LTS version (16.04):
https://www.digitalocean.com/community/tutorials/what-s-new-in-ubuntu-16-04#php-7

For OSX, we may add a link to https://php-osx.liip.ch/ to the README.

For the rest, manalize should never be used directly in production (where a restriction could exist) and

> any respectful developer should have the latest PHP version installed

Especially when we talk about PHP 7.
See #68
