### ISSUE TITLE
Consider using git diff & apply in order to setup & update envs

### ISSUE THREAD

**Issue by ogizanagi** [manala/manalize#64]
Replacing the `Dumper` class by applying a patch on the project may help supporting multi-envs.
Only the diff about what is missing for the project to comply the targeted env will be generated.

It may help merging existing files with necessary changes brung by the env resources (Makefile, .gitignore, ...).
If the patch cannot be applied due to conflict, we may suggest the user to create the patch and apply it interactively in order to resolve them.

The `Dumper` will only be kept in order to dump manalize metadata (we may also keep it in order to dump the env with resolved placeholders in a tmp directory though).

Drawbacks: it can only be applied on a git initialized repository (or we should fallback to the `patch` util).

**Comment by chalasr** [comment]
I never thought about this. 
👍  for letting git responsible of this part of the job (but only if we support the git version that is default installed on common unix-like distributions! :trollface:).

You may shoot me, but let's take the risk: If there's no repository, what about initializing an empty one (maybe after copying the whole project into a temp directory...)?

Otherwise, we can indeed fallback to the patch utility.

**Comment by ogizanagi** [comment]
> You may shoot me, but let's take the risk: If there's no repository, what about initializing an empty one (maybe after copying the whole project into a temp directory...)?

🔫 

No, actually I don't have much arguments against that, appart from the fact executing `manalize setup` on a wrong directory by mistake will init a new git repo. In my opinion, it's probably safer to abort the setup and ask the user to simply run `git init` if the repository isn't not initialized yet (or confirm the initialization).

>  for letting git responsible of this part of the job (but only if we support the git version that is default installed on common unix-like distributions! 

I hope it won't be an issue. (Only Travis' version was for the `diff` command, but only because it's an outdated one (< 2.0))

**Comment by chalasr** [comment]
> Drawbacks: it can only be applied on a git initialized repository (or we should fallback to the patch util).

Finally, it's fine to use `git diff` and `git apply` without any git repository 🎉
