### ISSUE TITLE
Create an installer script

### ISSUE THREAD

**Issue by ogizanagi** [manala/manalize#65]
Some projects like [`box-project/box2`](https://github.com/box-project/box2) suggests to use an installer in order to automatically download the last version of the tool, set proper rights and move it to the binaries directory.

``` sh
# README.md
$ curl -L https://github.com/manala/manalize/releases/download/v0.2.1/manalize.phar > /usr/local/bin/manalize
$ chmod +x /usr/local/bin/manalize
```

On our side, it'll allow to forget about editing `README.md` at each new version, as we can do api calls on github in order to retrieve the last version automatically.

From the user's perspective, you'll only have to ~~type~~ copy/paste the following line:

``` sh
$ curl -LSs https://github.com/manala/manalize/blob/master/installer.php | php
```

We can also host the script on a dedicated repository and make it available from a more user-friendly uri, for instance: http://www.manala.io/installer.php

**Comment by chalasr** [comment]
Looks like a great idea to me! 👍

**Comment by hyvs** [comment]
👍 interesting idea
